version: "3.8"

networks:
  app_network:
    driver: bridge

services:
  python_app:
    build:
      context: .
    networks:
      - app_network
    ports:
      - "5000:5000"

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - app_network
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    ports:
      - "3000:3000"
    networks:
      - app_network
    volumes:
      - grafana-data:/var/lib/grafana

volumes:
  grafana-data:
